### ISSUE TITLE
How to pip install addons from Pull Requests?

### ISSUE THREAD

**Issue by dreispt** [acsone/setuptools-odoo#102]
The documentaion provides this example:
```
pip install -e git+https://github.com/OCA/<repo>/<addon>#egg=odoo<8|9|10|11|12|13|14>-addon-<addon name>\&subdirectory=setup/<addon name>
```

I tried this:
```
pip install -e git+https://github.com/ursais/sale-workflow/tree/16.0-MIG-sale_order_line_menu/sale_order_line_menu#egg=odoo-addon-sale_order_line_menu|&subdirectory=setup/sale_order_line_menu
```
No output.

And then this:
```
pip install -e git+https://github.com/ursais/sale-workflow/tree/16.0-MIG-sale_order_line_menu/sale_order_line_menu#egg=odoo-addon-sale_order_line_menu
```
and got `fatal: repository 'https://github.com/ursais/sale-workflow/tree/16.0-MIG-sale_order_line_menu/sale_order_line_menu/' not found`.

What would be the right way to do this?
Is there a way to use a Pull Request reference instead of a branch reference?

Thanks

PS: The PR is https://github.com/OCA/sale-workflow/pull/2315

**Comment by dreispt** [comment]
Answer to self:
```
$ pip install -e git+https://github.com/ursais/sale-workflow@16.0-MIG-sale_order_line_menu#egg=odoo-addon-sale_order_line_menu\&subdirectory=setup/sale_order_line_menu
$ pip install -e git+https://github.com/OCA/sale-workflow@refs/pull/2315/head#egg=odoo-addon-sale_order_line_menu\&subdirectory=setup/sale_order_line_menu
```

**Comment by sbidoul** [comment]
@dreispt here is the relevant [pip documentation page](https://pip.pypa.io/en/stable/topics/vcs-support/) about all this.

NB: the page erroneously mentions that an editable install is required for pip freeze to work with VCS reference, which is not true anymore. So it is generally *not* necessary to use `-e` with VCS reference.

So a better recommendation is

`pip install git+https://github.com/ursais/sale-workflow@16.0-MIG-sale_order_line_menu#subdirectory=setup/sale_order_line_menu`

**Comment by sbidoul** [comment]
I updated the README at 6c0afb2b766e73360692b589b9f1034ce5b5fec3
