### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by salvorapi** [acsone/setuptools-odoo#110]
Hi,

in Windows environment, there is a problem with `clean_setup_addons_dir` at this line

https://github.com/acsone/setuptools-odoo/blob/4af31936bbc7db3b49b5c3d6b68f73f32efce731/setuptools_odoo/make_default_setup.py#L323

`rm -rf` doesn't exist on Windows system.

Salvo.

**Comment by sbidoul** [comment]
I'll welcome a PR to replace this with something else (such as `shutil.rmtree`).
