### ISSUE TITLE
Odoo 11 support (including Python 3)

### ISSUE THREAD

**Issue by sbidoul** [acsone/setuptools-odoo#16]
- [x] python 3 support (522d255ede683c06e552da8a419326ee80f65c4e, this solution works with python 3 only: the only solution that would work with both requires proper implementation of namespace packages, ie emptying `odoo/__init__.py`)
- [x] fix #10 
  - [x] Odoo patch (https://github.com/acsone/odoo/commit/b43e13e1e8bf6c3e647814771d11e37ab15bc81f)
  - [x] update `setuptools-odoo` core
  - [x] update `setuptools-odoo-make-default`
- [ ] update list of core addons
- [x] add some v11 addons in test data
- [x] update documentation

**Comment by sbidoul** [comment]
Given the current trend, I think `setuptools-odoo`'s Odoo 11 support will be for python 3 only.

Any comments about that?

**Comment by lmignon** [comment]
It's time to move forward... :+1:

**Comment by sbidoul** [comment]
I found a solution that works transparently on both python 2 and 3. One just needs to install odoo-autodiscover.

If https://github.com/odoo/odoo/pull/19517 is merged, then odoo-autodiscover is not necessary for v11 on python 3 but remains necessary for v11 on python 2.
