### ISSUE TITLE
Error to install from pip install

### ISSUE THREAD

**Issue by igallart** [acsone/setuptools-odoo#2]
In ubuntu 14.04 server 64b, with (sudo) pip install setuptools-odoo not is possible install:

Could not find a version that satisfies the requirement setuptools-odoo (from versions: 1.0.0b3, 1.0.0b5, 1.0.0b2, 1.0.0b2, 1.0.0b1, 1.0.0b3, 1.0.0b5, 1.0.0b1, 1.0.0b4, 1.0.0b4)
Cleaning up...
No distributions matching the version for setuptools-odoo

**Comment by sbidoul** [comment]
@igallart thanks for your interest in this project.

Can you provide more details on the exact steps to reproduce your issue?

I see you mention sudo. While it is probably not the source of your problem, I strongly recommand to use a virtualenv.

**Comment by igallart** [comment]
Hello @sbidoul, the steps are only install from pip:

With user root and not root but with sudo:

ej: sudo pip install setuptools-odoo 
or with user root: pip install setuptools-odoo

With the source from gitlab it yes is possible install, but command pip not. Is possible that was any error in package from pip?

**Comment by sbidoul** [comment]
Can you provide 

`python --version`
`pip --version`

I recommand upgrading pip to the latest version: `pip install --upgrade pip`

**Comment by igallart** [comment]
I updated pip and can install. Thanks

2016-05-09 12:30 GMT+02:00 Stéphane Bidoul (ACSONE) <
notifications@github.com>:
