### ISSUE TITLE
setuptools-odoo-make-default should suppress obsolete setup directories

### ISSUE THREAD

**Issue by sbidoul** [acsone/setuptools-odoo#21]
To be investigated.

- should it be an option or the default behaviour? => an option (--clean -c)
- it must clean setup directories corresponding to addons that are absent or not installable
- for addons in version >= 10, remove `setup/*/odoo_addons`
- for addons in version >= 11, remove `setup/*/odoo/__init__.py` and `setup/odoo/addons/__init__.py`
- OCA nightly script should be adapted to commit file removals to git (see #26)

**Comment by simahawk** [comment]
which are the side effects if we remove them? I think: none. 
If your setup is still pointing to a path that exists but does not link back to an existing module is going to fail in any case. At that point I prefer the setup path to not be found 1st.

**Comment by simahawk** [comment]
@sbidoul what if we simply delete them all and just run the create script again? 
Do we expect to have something to preserve there? If metadata always rely on manifest file I don't expect any issue. Am I missing something?

**Comment by sbidoul** [comment]
@simahawk we must preserve existing setups. They [can be](https://pypi.python.org/pypi/setuptools-odoo/2.0.2.post1#controlling-setuptools-odoo-behaviour) and [are](https://github.com/OCA/server-tools/blob/10.0/setup/server_environment/setup.py) modified manually sometimes.

**Comment by sbidoul** [comment]
Done in #28
