### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by spectra10008** [acsone/setuptools-odoo#22]
when i try to run odoo in linux ubuntu
 Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    __import__('pkg_resources').declare_namespace('odoo.addons')
ImportError: No module named pkg_resources

how can i solve it?

**Comment by sbidoul** [comment]
Can you please provide the exact steps you did to obtain this error? I've never seen it myself.

**Comment by sbidoul** [comment]
Also check that setuptools is installed in your environment.

**Comment by sbidoul** [comment]
Closing. Feel free to reopen with more details.
