### ISSUE TITLE
Does not work with plain tarballs of OCA modules

### ISSUE THREAD

**Issue by rhertzog** [acsone/setuptools-odoo#24]
When we create a Debian package, the basic expectation is that the source code is provided as a simple file archive, we then add packaging files in a debian sub-directory. For all Python modules, the packaging relies on the good old distutils approach (with some tweaks to alter path, etc.) but basically it still boils down to:
```console
$ python3 setup.py build
$ sudo python3 setup.py install
```

But this does not work at all with packages based on setuptools-odoo because it installs nothing (except the egg meta-information) because we are not in a git repository in this situation. Relying on git is perfectly fine when it comes to building release tarballs but it should not be needed to build and installl the source code.

It would be nice if setuptools-odoo could behave better when it detects that it's not in a git repository.

Steps to reproduce in a clean test chroot with Debian:
```console
$ sudo apt install python-pip3
$ sudo pip3 install setuptools-odoo
[...]
$ wget https://github.com/OCA/server-tools/archive/11.0.zip -O server-tools.zip
$ unzip server-tools.zip
[...]
$ cd server-tools-11.0/setup/auditlog/
$ python3 ./setup.py build
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
running build
running build_py
package init file 'odoo/addons/__init__.py' not found (or not a regular file)
running egg_info
creating odoo11_addon_auditlog.egg-info
writing odoo11_addon_auditlog.egg-info/PKG-INFO
writing dependency_links to odoo11_addon_auditlog.egg-info/dependency_links.txt
writing requirements to odoo11_addon_auditlog.egg-info/requires.txt
writing top-level names to odoo11_addon_auditlog.egg-info/top_level.txt
writing manifest file 'odoo11_addon_auditlog.egg-info/SOURCES.txt'
reading manifest file 'odoo11_addon_auditlog.egg-info/SOURCES.txt'
writing manifest file 'odoo11_addon_auditlog.egg-info/SOURCES.txt'
$ sudo python3 ./setup.py install
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
running install
running bdist_egg
running egg_info
writing odoo11_addon_auditlog.egg-info/PKG-INFO
writing dependency_links to odoo11_addon_auditlog.egg-info/dependency_links.txt
writing requirements to odoo11_addon_auditlog.egg-info/requires.txt
writing top-level names to odoo11_addon_auditlog.egg-info/top_level.txt
package init file 'odoo/addons/__init__.py' not found (or not a regular file)
reading manifest file 'odoo11_addon_auditlog.egg-info/SOURCES.txt'
writing manifest file 'odoo11_addon_auditlog.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying odoo11_addon_auditlog.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying odoo11_addon_auditlog.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying odoo11_addon_auditlog.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying odoo11_addon_auditlog.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying odoo11_addon_auditlog.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying odoo11_addon_auditlog.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg
creating /usr/local/lib/python3.6/dist-packages/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg
Extracting odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding odoo11-addon-auditlog 11.0.1.0.0 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg
Processing dependencies for odoo11-addon-auditlog==11.0.1.0.0
Searching for odoo<11.1dev,>=11.0a
Reading https://pypi.python.org/simple/odoo/
No local packages or working download links found for odoo<11.1dev,>=11.0a
error: Could not find suitable distribution for Requirement.parse('odoo<11.1dev,>=11.0a')
$ find /usr/local/lib/python3.6/dist-packages/odoo*
/usr/local/lib/python3.6/dist-packages/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg
/usr/local/lib/python3.6/dist-packages/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg/EGG-INFO
/usr/local/lib/python3.6/dist-packages/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg/EGG-INFO/top_level.txt
/usr/local/lib/python3.6/dist-packages/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg/EGG-INFO/not-zip-safe
/usr/local/lib/python3.6/dist-packages/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg/EGG-INFO/SOURCES.txt
/usr/local/lib/python3.6/dist-packages/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg/EGG-INFO/PKG-INFO
/usr/local/lib/python3.6/dist-packages/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg/EGG-INFO/dependency_links.txt
/usr/local/lib/python3.6/dist-packages/odoo11_addon_auditlog-11.0.1.0.0-py3.6.egg/EGG-INFO/requires.txt
```

/cc @sbrun

**Comment by sbidoul** [comment]
This does not work indeed with "dumb" source tarball. It should work with tarballs generated with setup.py sdist.

Have you tried:

- python setup.py sdist
- unpack the generated tarball
- then python setup.py install

This should work because the sdist contains the required PKG-INFO metadata.

**Comment by rhertzog** [comment]
Thanks for the suggestion. I will have a look at this.

But then we have multiple tarballs for each git repository, not really ideal in particular since we have no way to download new release tarballs automatically (we have infrastructure to fetch github tarballs for new releases, or pypi tarballs for new releases on pypi, but nothing to do this "sdist" work automatically even more when it needs to happen in a sub-directory of a github repo).

And creating release tarballs is not really the job of the packager. Could OCA modules upload such release tarballs on pypi and not only the wheels?

**Comment by sbidoul** [comment]
> Could OCA modules upload such release tarballs on pypi and not only the wheels?

That would make sense indeed.

I'm wondering: is it possible in theory to build .deb from .whl (which contain all meta data)?

**Comment by rhertzog** [comment]
> That would make sense indeed.

What is required to make this happen?

> I'm wondering: is it possible in theory to build .deb from .whl (which contain all meta data)?

I asked myself the same question... I think it's possible in theory but sofar we don't have the required infrastructure on the Debian side. Compare for example our release monitoring system:
http://pypi.debian.net/setuptools-odoo => has tarballs
http://pypi.debian.net/odoo11-addon-auditlog => has no tarballs

Also it's not a good fit for compiled extensions. AFAIK a wheel would provide a compiled extension ready to use and we want the source code to build it instead. All our packaging infrastructure expects to be able to run the setup.py and with a wheel, this would never be the case.

**Comment by sbidoul** [comment]
> What is required to make this happen?

The build and pypi upload process runs nightly on OCA servers. 

Building and uploading sdists involves updating [bdist_all_wheels](https://github.com/OCA/maintainer-tools/blob/master/tools/bdist_all_wheels.py), [wh2simple](https://github.com/OCA/maintainer-tools/blob/master/tools/wh2simple.py) and [pypi_upload_wheels](https://github.com/OCA/maintainer-tools/blob/master/tools/pypi_upload_wheels.py).

It's not hard, but not exactly trivial either.

**Comment by sbidoul** [comment]
@rhertzog do you have a specific urgency for this? Do not hesitate to PM me if you want to discuss.

**Comment by rhertzog** [comment]
Thanks, I will get back to you when I'm tackling this topic. But I would not mind if someone else ensures that OCA is uploading source tarballs as well as wheels. I just filed a ticket for this: https://github.com/OCA/maintainer-tools/issues/331

**Comment by sbidoul** [comment]
Well I'm afraid that someone else would be me :)

**Comment by sbidoul** [comment]
I'm closing this in favor of https://github.com/OCA/maintainer-tools/issues/331
