### ISSUE TITLE
Include mapping for OpenSSL package in setuptools-odoo

### ISSUE THREAD

**Issue by jaumeplanas** [acsone/setuptools-odoo#30]
@sbidoul  Please consider to add a new mapping for OpenSSL package in [external_dependencies.py](https://github.com/acsone/setuptools-odoo/blob/master/setuptools_odoo/external_dependencies.py)

This dependency is very common in OCA/l10n-spain and it's very tedious to be always patching this requirement.

If you prefer, I can open a PR against that.

Thanks

**Comment by sbidoul** [comment]
Done in 894af70b07839a9322ed8b8e7b332d152dc59e58

**Comment by jaumeplanas** [comment]
OK, thanks!
