### ISSUE TITLE
Odoo depends not in same package 

### ISSUE THREAD

**Issue by jo541** [acsone/setuptools-odoo#35]
I have 2 Odoo packages . Tools and Global. In global there is a Odoo module name contact map and in tools there is a Odoo module name map.

Contact map has a dependency with map. but when I install the packages with odoo setuptools. I have a error message . Because missing requirement depends. 

I used a requirement file like this. 
-e git+git-url@branch#egg=odoo12-addon-tools\&subdirectory=setup/tools
-e git+git-url@branch#egg=odoo12-addon-global\&subdirectory=setup/global

My question is. The depends must be in the same package ? Or I have the possibility to force install of package before download the next ?

**Comment by lmignon** [comment]
Hi @jo541 
> I have 2 Odoo packages . Tools and Global. In global there is a Odoo module name contact map and in tools there is a Odoo module name map.
Do you mean that you have 2 repositories:
* repo-tools
* repo-global

with the addon `map`into the `repo-tools` repository and the addon `contact` into the  `repo-global` repository ?

If it's the case, your folders  should looks like:

repo-tools
repo-tools/map
repo-toos/setup/map
repo-global
repo-global/contact
repo-global/setup/contact

With this kind of structure, your requirements file should looks like:
-e git+git-ur/repo-tools@branch#egg=odoo12-addon-map&subdirectory=setup/map
-e git+git-url/repo-global@branch#egg=odoo12-addon-contact&subdirectory=setup/contact

**Comment by jo541** [comment]
Hi @lmignon,

> with the addon mapinto the repo-tools repository and the addon contact into the repo-global repository ?

Yes. But It's not a repertory with multi module.

My folders are like this. (I'm work in V12)

repo-tools
repo-tools/setup
repo-tools/setup/tools
repo-tools/setup/tools/setup.py
repo-tools/setup/tools/odoo
repo-tools/setup/tools/odoo/addons
repo-tools/setup/tools/odoo/addons/map
repo-tools/setup/tools/odoo/addons/module2
repo-tools/setup/tools/odoo/addons/module3

repo-global/setup
repo-global/setup/global
repo-global/setup/global/setup.py
repo-global/setup/global/odoo
repo-global/setup/global/odoo/addons
repo-global/setup/global/odoo/addons/contact
repo-global/setup/global/odoo/addons/module2
repo-global/setup/global/odoo/addons/module3

**Comment by lmignon** [comment]
@jo541 How did you generate the setup of your repository? Do you use the [setuptools-odoo-make-default helper script](https://github.com/acsone/setuptools-odoo#setuptools-odoo-make-default-helper-script) ? The directory structure described does not seem to me conform to what is expected to work with setuptools-odoo

**Comment by sbidoul** [comment]
@jo541 at first glance that directory structure should work. Can you provide more details? Exact error message, content of setup.py etc.

**Comment by jo541** [comment]
@lmignon 
My setup.py files:
For Global
```python
import setuptools

setuptools.setup(
    name='Global',
    version="12.0.0.0.0.1",
    setup_requires=['setuptools-odoo'],
    odoo_addons=True,
)
```

```python
import setuptools

setuptools.setup(
    name='Tools',
    version="12.0.0.0.0.1",
    setup_requires=['setuptools-odoo'],
    odoo_addons=True,
)
```

@sbidoul 
My error is   Could not find a version that satisfies the requirement odoo12-addon-maps (from global->-r requirement/gitlab_requirement.txt (line 3)) (from versions: )
No matching distribution found for odoo12-addon-maps (from global->-r requirement/gitlab_requirement.txt (line 3))

**Comment by sbidoul** [comment]
That's because the distribution where the map addon can be found is named `Global`, not `odoo12-addon-maps`.

Since you have multiple addons in your global package, you need to tell it explicitly in which package the maps addon can be found.

You can do that by adding a [depends_override](https://github.com/acsone/setuptools-odoo#controlling-setuptools-odoo-behaviour) section in the setup.py of your tools package.

Something like `'map': 'Global'`.

I'd recommend more specific package names, btw.

**Comment by jo541** [comment]
@sbidoul ,

But if my folder with module map contain on other modules, I can't set name="odoo12-addons-maps" in my setup.py? 

Global and tools contains multi modules.

**Comment by jo541** [comment]
And if I had in setup.py this code. 
odoo_addon={
        'depends_override': {
            'maps': 'Tools',
        },
    },

I have an error . 

> Command "python setup.py egg_info" failed with error code 1 in /Users/allotools/Documents/allotools/gitlab/src/odoo12-addon-odoo-at-global/setup/odoo-at-global

**Comment by jo541** [comment]
Ok I just change odoo_addon by odoo_addons and now it's work.

Thank you for your help and thank you for the tools 👍 .
