### ISSUE TITLE
Installation by pip

### ISSUE THREAD

**Issue by Kerrim-** [acsone/setuptools-odoo#38]
Hi,
I'm not sure if we are missing something but recently our whl packages stopped recognizing the installed odoo version.

Installed is 12.0.postXXXXXXXX and the package checks for 12.0a <= odoo < 12.1dev.
https://github.com/acsone/setuptools-odoo/blob/744dc7723423e015c664f19c849ccf1f065ad3ee/setuptools_odoo/core.py#L67

This started happening some days ago. We fixed it by providing a fake odoo package with the right version number.

So my question: is this a bug in setuptools or does anyone experience the same issue?

**Comment by sbidoul** [comment]
You mean the installed version is truly 12.0.postXXXXXXXX (with the X)? Or is it something like 12.0.post20190501.

**Comment by Kerrim-** [comment]
sorry the XXXs are a placeholder for the date :)

**Comment by sbidoul** [comment]
That's strange, I do not experience this, and these version work fine:

![image](https://user-images.githubusercontent.com/692075/59681232-b0b09400-91d3-11e9-858d-8f895572dff3.png)

Can you provide detailed steps to reproduce?

**Comment by Kerrim-** [comment]
Ok I tested it and you are right. I get the same behavior on the system:

```
>>> from packaging import version, specifiers
>>> odoo12 = version.parse("12.0.post20190601")
>>> intervall = specifiers.SpecifierSet("<12.1dev,>=12.0a")
>>> intervall.contains(odoo12)
True
```

I could narrow my problem down to the force-reinstall parameter of odoo. So I don't think that this is an setuptools issue anymore.

Thanks for the fast reply.
