### ISSUE TITLE
No matching distribution found for odoo10-addon-payment_stripe_sca

### ISSUE THREAD

**Issue by eLBati** [acsone/setuptools-odoo#43]
I have a custom module that depends on `payment_stripe_sca`.
While installing it by pip, I get
```
Collecting odoo10-addon-payment_stripe_sca (from odoo10_addon_MODULE->-r config/requirements.txt (line 141))
  ERROR: Could not find a version that satisfies the requirement odoo10-addon-payment_stripe_sca (from odoo10_addon_MODULE->-r config/requirements.txt (line 141)) (from versions: none)
ERROR: No matching distribution found for odoo10-addon-payment_stripe_sca (from odoo10_addon_MODULE->-r config/requirements.txt (line 141))
```
but `payment_stripe_sca` is included in odoo so pip should not search for a single package.

Do you know why it happens?

Thanks

**Comment by sbidoul** [comment]
setuptools-odoo has special knowledge of the core Odoo addons.
payment_stripe_sca was added in https://github.com/acsone/setuptools-odoo/commit/12b25893a7615aec788854bfbc2820f940e2b60d (2.5.1).

So I'd say you have an old setuptools-odoo lying around in some `.eggs` directory or in your environment.

**Comment by eLBati** [comment]
Thanks!
