### ISSUE TITLE
add a "-v" switch with verbose output

### ISSUE THREAD

**Issue by mimusica** [acsone/setuptools-odoo#46]
add a "-v" switch with verbose output

**Comment by sbidoul** [comment]
can you elaborate what problem you are trying to solve?

**Comment by mimusica** [comment]
Currently I'm trying to migrate 'base_phone' to 13.0.
The module is dependent on the 'phonenumbers' python library and I'm trying
to find a solution to have it automatically installed when you install the
module in odoo.
Anyway, for debugging purposes, the "-v" flag might come in handy.

Op ma 3 aug. 2020 om 12:43 schreef Stéphane Bidoul <notifications@github.com

**Comment by sbidoul** [comment]
@mimusica add phonenumbers to the `external_dependencies` dictionary of the manifest. That should be sufficient.
