### ISSUE TITLE
Generate requirements: duplicated entries when specific version pinned

### ISSUE THREAD

**Issue by simahawk** [acsone/setuptools-odoo#59]
Specific version pinned https://github.com/OCA/rest-framework/blob/14.0/base_rest/__manifest__.py#L27 leads to duplicated entries into requirements.txt:

![image](https://user-images.githubusercontent.com/347149/134023264-d33f3179-df0d-4053-b4a7-746f5cc9c4b7.png)

Example: https://github.com/OCA/rest-framework/runs/3652923710#step:4:164

CC @lmignon

**Comment by sbidoul** [comment]
Does this cause issues in practice ?

**Comment by simahawk** [comment]
The final result seems correct anyway but in the case of lower pinning you get 2 downloads. Eg:

```
$ cat test-bad-requirements.txt 
apispec
apispec<5.1.0

$ pip install -r test-bad-requirements.txt --no-cache-dir
Collecting apispec
  Downloading apispec-5.1.0-py2.py3-none-any.whl (28 kB)
  Downloading apispec-5.0.0-py2.py3-none-any.whl (28 kB)
Installing collected packages: apispec
Successfully installed apispec-5.0.0
```

Greater pinning (same case as base_rest):
```
$ cat test-bad-requirements.txt 
apispec
apispec>=4.0.0

$ pip install -r test-bad-requirements.txt --no-cache-dir
Collecting apispec
  Downloading apispec-5.1.0-py2.py3-none-any.whl (28 kB)
Installing collected packages: apispec
Successfully installed apispec-5.1.0
```
So, not really harmful, but still weird and sub-optimal if we have many duplicated entries.
In fact, this does not happen that often...
