### ISSUE TITLE
[blueprint] change package naming structure to odoo{series}-addon-addon_name-{version}

### ISSUE THREAD

**Issue by sbidoul** [acsone/setuptools-odoo#6]
After more than six months intensive usage setuptools-odoo proves to be very robust. There is only one item that I would like to change before moving out of beta.

Until now, setuptools-odoo generates package names with the following structure: `odoo-addon-addon_name-{series}.{version}`. In this scheme, series.version (ie 9.0.2.0.0) constitutes the python package version. The series is usually autodetected from the odoo manifest.

This has several implications:
- typing 'pip install odoo-addon-addon_name' without specifying a version will look and possiblty try to install addon for the wrong Odoo version;
- to mitigate this risk, in OCA there is a different directory of each odoo series (ie oca-8.0, oca-9.0, etc), and developers are expected to use the correct one in their --find-links options; this is cumbersome and hinders discovery of unported addons;
- if we want to publish addons to pypi, this is a problem, as pypi by default shows the last version of a package; although it is possible to have multiple visible versions, it seems the management of such visible versions is manual and not exposed through an official PyPI api (see https://github.com/acsone/setuptools-odoo/issues/6#issuecomment-244600981); 
- if all addons for different Odoo series were published in the same warehouse (such as PyPI or wheelhouse.odoo-community.org/oca), devs would need to put explicit version requirements when installing addons eg: `pip install odoo-addon-connector>=9.0a,<9.1a` vs a simpler `odoo9-addon-connector`;
- similarly, when all addons for different series are in the same warehouse, `pip install --upgrade` will possibly upgrade addons to an upper Odoo series without warning, which is not desirable.

This makes me think the same addon for different Odoo series must be considered as different packages.

So I'm considering to change the package naming scheme  to `odoo{series}-addon-{version}`. where series is eg 8, 9, 10, and version is the addon version as found in the Odoo manifest, eg:
- `odoo9-addon-addon_name-9.0.2.0.0`
- `odoo8-addon-addon_name-8.0.1.0.5`
- `openerp7-addon-addon_name-1.5.0`

The change in setuptools-odoo to implement this is [relatively minor](https://github.com/acsone/setuptools-odoo/compare/breaking).

At the same time the wheel generator on wheelhouse.odoo-community.org would also change to generate all wheels to the same directory: https://wheelhouse.odoo-community.org/oca.

This is a breaking change as existing build scripts would require slight updates to reference the new OCA wheelhouse location. `setup.py` having explicit references to odoo addons in their install_require sections or requirements.txt files will need to be updated to use the new naming scheme.

setuptools-odoo will support a SETUPTOOL_ODOO_LEGACY_MODE environment variable that enables the current behaviour to ease the transition period.

TODO
- [x] update setuptools-odoo
- [x] update bdist_all_wheels in OCA/maintainer-tools https://github.com/acsone/maintainer-tools/tree/bdist-wheel-newstyle-sbi
- [x] update wheel generation scripts on wheelhouse.odoo-community.org
- [x] PR of https://github.com/acsone/maintainer-tools/tree/bdist-wheel-newstyle-sbi to OCA/maintainer-tools
- [x] update wheelhouse.odoo-community.org index page
- [x] update blog post on odoo-community.org
- [x] release setuptools-odoo 1.0.0b7
- [x] announce release

**Comment by lmignon** [comment]
> if we want to publish addons to pypi, this is a problem, as pypi is designed to show the last version of a package; the current scheme makes it impossible to have pypi show the package for Odoo 8, 9, 10 at the same time; this is the most problematic

@sbidoul in pypi, you can specify the list of versions to display for a package. This feature is available into the management interface of your packages. 
Exemple with pycoda: (reverted after the test)
![configure_visibility](https://cloud.githubusercontent.com/assets/544090/18230917/10146314-72aa-11e6-9129-58e4529062ba.png)
![list packages](https://cloud.githubusercontent.com/assets/544090/18230920/1722f0da-72aa-11e6-957c-1c9078a41e01.png)
Nevertheless, I don't know if an api exists to control the list of visible versions.

**Comment by sbidoul** [comment]
@lmignon thanks for the pointer. I updated the description accordingly.

**Comment by sbidoul** [comment]
I added a new argument:

- if all addons for different Odoo series were published in the same repository (such as PyPI or wheelhouse.odoo-community.org/oca), devs would need to put explicit version requirements when installing addons eg: `pip install odoo-addon-connector>=9.0a,<9.1a` vs a simpler `odoo9-addon-connector`.

**Comment by sbidoul** [comment]
I added a new argument:
- similarly, when all addons for different series are in the same warehouse, `pip install --upgrade` will possibly upgrade addons to an upper Odoo series without warning, which is not desirable.

**Comment by lasley** [comment]
I support this, but could we possibly do `odoo-{series}-addon-{version}`? 

I feel adding the dash between odoo version and series is more consistent with the dash between addon and version.

**Comment by lmignon** [comment]
:+1:  @sbidoul You have convinced me. Even if you provide a backward compatibility layer, the transition seems very easy to manage.
About the naming convention even if I understand the motivation of @lasley  I'm for your initial proposal. (odoo9, odoo8) since it's more in the spirit to consider odoo8, odoo9, odoo10 as different packages and not as a new version of a same package.

**Comment by sebastienbeau** [comment]
I agree to consider odoo 8, 9, 10 as a different package :+1:

**Comment by max3903** [comment]
:+1:

**Comment by cezarsantanna** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
:+1:

**Comment by sbidoul** [comment]
Thanks for the feedback. I merged on master. This will be in the next release.

@lasley I prefer `odoo9-addon-...` over `odoo-9-addon-...` because having something that looks like a version number (ie 9) in the middle of the package name could confuse some tools.

**Comment by sbidoul** [comment]
All done, let me know of any issue.
