### ISSUE TITLE
Install Odoo 15 addon. Fail does not look like an Odoo addon package name

### ISSUE THREAD

**Issue by isares-br** [acsone/setuptools-odoo#70]
After investigate, I found that it was because of this RE is not matching with new package name of version 15.0

[METADATA_NAME_RE = re.compile(r"^odoo(\d+)-addon-(?P<addon_name>.*)$")](https://github.com/acsone/setuptools-odoo/blob/7db9784e2e103413f2e5bb62eed9592584fb4407/setuptools_odoo/core.py#L24)

**Comment by sbidoul** [comment]
@isares-br thanks for the fix. I included it in #72 with a test.

Out of curiosity, how did you trigger this bug ?

**Comment by isares-br** [comment]
Build an Odoo 15.0 module as Pypi package and install it.

**Comment by sbidoul** [comment]
There must be something else, since this was working correctly in OCA since a couple of months.

**Comment by isares-br** [comment]
Not sure for that. I'm using pre-commit and create package with GitHub Actions, then build a docker image that install it inside.
